name: Build and publish Docker image workflow

on:
  workflow_call:
    inputs:
      registry:
        description: "Image registry used by this project"
        required: true
        type: string
    secrets:
      registry-username:
        description: "Docker Registry Username used for this project"
        required: true
      registry-token:
        description: "Token used for Docker Registry authentication"
        required: true

defaults:
  run:
    shell: bash

jobs:
  docker:
    permissions:
      contents: read
      packages: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        env:
          SHA: ${{ github.event.pull_request.head.sha || github.event.after }}
        with:
          ref: ${{ env.SHA }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-token }}

      - name: Populate and extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ${{ inputs.registry }}/cleanup
          flavor: |
            latest=true
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: compare,recommendations
          image: ${{ steps.meta.outputs.tags }}
          to: ${{ inputs.registry }}/cleanup:latest
          ignore-unchanged: true
          only-severities: critical,high
          write-comment: true
          keep-previous-comments: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
