name: Create tag and release workflow

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Create a new release along with the release notes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub release from tag
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true