name: Feature branches workflow

on:
  push:
    branches:
      - feature/*
      - feat/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: loureirovinicius/cleanup/.github/workflows/lint.yaml@master

  build-application:
    uses: loureirovinicius/cleanup/.github/workflows/build-application.yaml@master
    with:
      upload-binary: true

  download-binary:
    name: Download Cleanup binary generated
    runs-on: ubuntu-latest
    needs: build-application
    steps:
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: cleanup_binary


  
  

    
  