name: Feature branches workflow

on:
  push:
    branches:
      - feature/*
      - feat/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: loureirovinicius/cleanup/.github/workflows/lint.yaml@feat/ci-cd

  build-application:
    uses: loureirovinicius/cleanup/.github/workflows/build-application.yaml@feat/ci-cd

  upload-binary:
    name: Upload last binary file generated to PR
    runs-on: ubuntu-latest
    needs: build-application
    steps:
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: Cleanup binary file
          path: cleanup

  
  

    
  