# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:

  setup-environment:
    runs-on: ubuntu-latest
    name: Checkout and Set up Go
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache-dependency-path: "**/*.sum"

    - name: Display Go version
      run: go version

    - name: Install code dependencies
      run: go get ./... 

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Test code
      run: go test -json -v ./... > TestResults.json

    - name: Upload code test results
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: TestResults.json

  build:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Build code    
        run: go build -v -o cleanup ./cmd/main.go