name: Publish new release

on:
  push:
    branches:
      - feat/ci-cd
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: loureirovinicius/cleanup/.github/workflows/lint.yaml@master

  build-application:
    uses: loureirovinicius/cleanup/.github/workflows/build-application.yaml@master

  build-and-publish-image:
    needs: build-application
    uses: loureirovinicius/cleanup/.github/workflows/build-and-publish-image.yaml@master
    with:
      registry: loureirovini
    secrets:
      registry-username: ${{ secrets.REGISTRY_USERNAME }}
      registry-token: ${{ secrets.REGISTRY_TOKEN }}

  create-tag-and-release:
    needs: build-and-publish-image
    uses: loureirovinicius/cleanup/.github/workflows/create-tag-and-release.yaml@master