name: Publish new release

on:
  push:
    branches:
      - feat/ci-cd
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  lint:
    uses: loureirovinicius/cleanup/.github/workflows/lint.yaml@feat/ci-cd

  build-application:
    needs: lint
    uses: loureirovinicius/cleanup/.github/workflows/build-application.yaml@feat/ci-cd

  build-and-publish-image:
    needs: build-application
    uses: loureirovinicius/cleanup/.github/workflows/build-and-publish-image.yaml@feat/ci-cd
    with:
      registry: "loureirovini"
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_token: ${{ secrets.REGISTRY_TOKEN }}

  create-tag-and-release:
    needs: build-and-publish-image
    uses: loureirovinicius/cleanup/.github/workflows/build-and-publish-image.yaml@feat/ci-cd